#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


# Rodar o phpstan
./vendor/bin/phpstan
# Verifica se o retorno do phpstan não é um erro
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar..."
    exit 1;
fi;


# Formatar cada arquivo alterado usando Laravel pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}")

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}"
    git add "${FILE}"
done;
